# vm3_forms.json (measure.py table) + образы all*.mem -> vm3_timing_table.inc
#
#   py gen_table3.py REF <файл .inc> <такты на шаг сдвига ASH/ASHC>
#
# Время формы снимается при ответе памяти через REF и REF + 2 тактов. От
# задержки оно не линейно: при малой цикл шины прячется за микропрограммой, при
# большой шина ждёт сама (MOV (R),@(R)+ - 36, 43, 51 при 2, 4, 6). Поэтому в
# таблице - время при REF (VM3_FORM_CLOCKS) и прирост на 2 такта задержки
# (VM3_FORM_SLOPE2), которым ядро поправляет другую задержку. Номер формы - как
# у Vm1BusTiming::form2_of() по коду первой копии. Форма, которую стенд не снял
# (ловушка, нет случая), остаётся нулём: ядро считает её по старым формулам.
import sys, json, glob, collections

F2_DOUBLE = 0
F2_SINGLE = F2_DOUBLE + 12 * 256
F2_EIS = F2_SINGLE + 28 * 16
F2_XOR = F2_EIS + 5 * 16
F2_JMP = F2_XOR + 16
F2_JSR = F2_JMP + 16
F2_RTS = F2_JSR + 16
NAMES = ['RTS', 'RTI', 'RTT', 'TRAP', 'MARK', 'CC_CLEAR', 'CC_SET', 'BR_TAKEN', 'BR_NOT',
         'SOB_TAKEN', 'SOB_NOT', 'INTERRUPT', 'INTERRUPT_VIRQ', 'WAIT', 'RESET']
F2 = {n: F2_RTS + i for i, n in enumerate(NAMES)}
F2_COUNT = F2_RTS + len(NAMES)

DOUBLE_INDEX = [-1, 0, 1, 2, 3, 4, 5, -1, -1, 6, 7, 8, 9, 10, 11, -1]
SINGLE_OPS = [0o0050, 0o0051, 0o0052, 0o0053, 0o0054, 0o0055, 0o0056, 0o0057, 0o0060, 0o0061,
              0o0062, 0o0063, 0o0003, 0o0067, 0o1050, 0o1051, 0o1052, 0o1053, 0o1054, 0o1055,
              0o1056, 0o1057, 0o1060, 0o1061, 0o1062, 0o1063, 0o1064, 0o1067]


def spec(sp):
    return ((sp >> 3) & 7) * 2 + (1 if (sp & 7) == 7 else 0)


def form2_of(w, taken, div_v):
    if (w & 0o170000) == 0o070000:
        op = (w >> 9) & 7
        if op <= 3:
            e = 4 if (op == 1 and div_v) else op
            return F2_EIS + e * 16 + spec(w & 0o77)
    di = DOUBLE_INDEX[w >> 12]
    if di >= 0:
        return F2_DOUBLE + (di * 16 + spec((w >> 6) & 0o77)) * 16 + spec(w & 0o77)
    if ((w >> 6) & 0o1777) in SINGLE_OPS:
        return F2_SINGLE + SINGLE_OPS.index((w >> 6) & 0o1777) * 16 + spec(w & 0o77)
    if (w & 0o177000) == 0o074000: return F2_XOR + spec(w & 0o77)
    if (w & 0o177700) == 0o000100: return F2_JMP + spec(w & 0o77)
    if (w & 0o177000) == 0o004000: return F2_JSR + spec(w & 0o77)
    if (w & 0o177770) == 0o000200: return F2['RTS']
    if (w & 0o177000) == 0o077000: return F2['SOB_TAKEN' if taken else 'SOB_NOT']
    b = w & 0o177400
    if (0o400 <= b <= 0o3400) or (0o100000 <= b <= 0o103400):
        return F2['BR_TAKEN' if taken else 'BR_NOT']
    if b in (0o104000, 0o104400) or w in (3, 4, 0): return F2['TRAP']
    if w == 2: return F2['RTI']
    if w == 6: return F2['RTT']
    if (w & 0o177700) == 0o006400: return F2['MARK']
    if (w & 0o177740) == 0o000240: return F2['CC_SET' if w & 0o20 else 'CC_CLEAR']
    return None


def main():
    ref, out, shift = int(sys.argv[1]), sys.argv[2], int(sys.argv[3])
    r1, r2 = str(ref), str(ref + 2)
    times = json.load(open('vm3_forms.json'))
    clocks = [0] * F2_COUNT
    slope = [0] * F2_COUNT
    odd = []
    for part in sorted(glob.glob('all*.json')):
        mem = [int(l, 16) for l in open(part[:-5] + '.mem')]
        for c in json.load(open(part)):
            name = c['name']
            t = times.get(name)
            if name == 'SOB loop' or not t or t.get(r1) is None or t.get(r2) is None:
                continue
            w = mem[c['copies'][0] >> 1]
            f = form2_of(w, not name.endswith('not'), name.startswith('DIVV'))
            if f is None:
                continue
            t1, t2 = t[r1], t[r2]
            if t1 != int(t1) or t2 != int(t2) or not (0 < t1 < 256) or not (0 <= t2 - t1 < 128):
                odd.append((name, t1, t2)); continue
            if clocks[f] and (clocks[f], slope[f]) != (int(t1), int(t2 - t1)):
                odd.append(('dup ' + name, t1, t2, clocks[f], slope[f]))
            clocks[f] = int(t1); slope[f] = int(t2 - t1)
    # SOB: виток SOB R,. - 17 тактов и ответ (снято отдельно)
    clocks[F2['SOB_TAKEN']] = 17 + ref; slope[F2['SOB_TAKEN']] = 2
    n = sum(1 for x in clocks if x)
    with open(out, 'w', newline='\n') as fh:
        fh.write('// Generated by tools/vm3-timing/gen_table3.py - do not edit.\n')
        fh.write('// КМ1801ВМ3 form clocks at a memory reply of VM3_REF_REPLY clocks, and what\n')
        fh.write('// 2 more reply clocks add, for every Vm1BusTiming::form2_of() form;\n')
        fh.write('// 0 - not measured (old formulas). %d of %d forms from the chip model\n' % (n, F2_COUNT))
        fh.write('static const unsigned int VM3_REF_REPLY = %d;\n' % ref)
        fh.write('static const uint8_t VM3_FORM_CLOCKS[%d] = {\n' % F2_COUNT)
        for i in range(0, F2_COUNT, 16):
            fh.write('    ' + ', '.join('%3d' % x for x in clocks[i:i + 16]) + ',\n')
        fh.write('};\nstatic const uint8_t VM3_FORM_SLOPE2[%d] = {\n' % F2_COUNT)
        for i in range(0, F2_COUNT, 16):
            fh.write('    ' + ', '.join('%2d' % x for x in slope[i:i + 16]) + ',\n')
        fh.write('};\n')
        fh.write('// Clocks each step of an ASH or ASHC shift adds\n')
        fh.write('static const unsigned int VM3_SHIFT_CLOCKS = %d;\n' % shift)
    print('measured', n, 'of', F2_COUNT)
    print('slope histogram', sorted(collections.Counter(slope[i] for i in range(F2_COUNT) if clocks[i]).items()))
    for o in odd[:40]:
        print('odd', o)


if __name__ == '__main__':
    main()
