#!/bin/bash
#
# Release build for Linux x86_64: one AppImage per renderer, via linuxdeployqt.
#
# Qt is linked dynamically here on purpose -- the AppImage bundles the Qt
# libraries it actually needs, and a shared build keeps compatibility with a
# wider range of distributions (see BUILD.md).
#
# Usage: ./build-linux.sh [clean]

set -euo pipefail

ARCHITECTURE="x86_64"
PLATFORM="linux"
QT_PATH="${HOME}/Qt/6.8.2/gcc_64"
LINUXDEPLOYQT="${HOME}/Downloads/linuxdeployqt-continuous-x86_64.AppImage"

# SDL2 is not built here: the AppImage would have to carry libSDL2, and the Qt
# and OpenGL renderers already cover this platform.
RENDERERS=("qt" "opengl")

cd "$(dirname "$0")"
BUILD_ROOT="$(pwd)"

if [ ! -x "${LINUXDEPLOYQT}" ]; then
    echo "ERROR: linuxdeployqt not found or not executable: ${LINUXDEPLOYQT}" >&2
    exit 1
fi

if [ ! -d "${QT_PATH}" ]; then
    echo "ERROR: Qt not found at ${QT_PATH}" >&2
    exit 1
fi

# The project() call in src/CMakeLists.txt is the single source of truth for the
# version. globals.h carries the same number but is generated by cmake, so it is
# only in sync after a configure run.
APP_VERSION=$(sed -n 's/^project(.* VERSION \([0-9.]*\).*/\1/p' ../src/CMakeLists.txt)
if [ -z "${APP_VERSION}" ]; then
    echo "ERROR: cannot read the project version from ../src/CMakeLists.txt" >&2
    exit 1
fi

echo "Building eCat3 ${APP_VERSION} for ${PLATFORM} ${ARCHITECTURE}"
mkdir -p release

for RENDERER in "${RENDERERS[@]}"; do
    echo
    echo "=== Renderer: ${RENDERER}"

    BUILD_DIR="${BUILD_ROOT}/build/${PLATFORM}-${ARCHITECTURE}-${RENDERER}"
    RELEASE_NAME="ecat-${APP_VERSION}-${PLATFORM}-${ARCHITECTURE}-${RENDERER}"
    RELEASE_DIR="${BUILD_ROOT}/release/${RELEASE_NAME}.AppDir"
    RESOURCES="${RELEASE_DIR}/usr/share/ecat"

    if [ "${1:-}" = "clean" ]; then
        rm -rf "${BUILD_DIR}"
    fi

    # Always reconfigure and rebuild: cmake and ninja work out what actually
    # changed, and a stale executable never reaches the AppImage.
    cmake -S ../src -B "${BUILD_DIR}" -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="${QT_PATH}" \
        -DRENDERER_${RENDERER^^}=1
    cmake --build "${BUILD_DIR}"

    # The AppDir is recreated from scratch, otherwise leftovers from an earlier
    # build (configs of a machine that was renamed, say) end up in the AppImage.
    rm -rf "${RELEASE_DIR}"
    mkdir -p "${RELEASE_DIR}/usr/bin" "${RESOURCES}"
    cp -r ./.linux/ecat3.AppDir/* "${RELEASE_DIR}"
    cp "${BUILD_DIR}/eCat3" "${RELEASE_DIR}/usr/bin/"

    # deploy/ecat.ini is the developer's own working copy and must not be
    # released -- the distributed defaults live in deploy/.ecat.ini.
    cp -r ../deploy/* "${RESOURCES}"
    rm -f "${RESOURCES}/ecat.ini"
    cp ../deploy/.ecat.ini "${RESOURCES}/ecat.ini"

    (
        cd release
        # linuxdeployqt names the image after the .desktop entry and $VERSION.
        export VERSION="${APP_VERSION}-${PLATFORM}-${RENDERER}"
        rm -f "eCat3-${VERSION}-${ARCHITECTURE}.AppImage" "${RELEASE_NAME}.AppImage"
        "${LINUXDEPLOYQT}" \
            "${RELEASE_DIR}/usr/share/applications/ecat3.desktop" \
            -verbose=1 \
            -appimage \
            -no-translations \
            -no-copy-copyright-files \
            -qmake="${QT_PATH}/bin/qmake"
        mv "eCat3-${VERSION}-${ARCHITECTURE}.AppImage" "${RELEASE_NAME}.AppImage"
    )
done

echo
echo "=== Release contents:"
ls -l release/*.AppImage
