#!/bin/bash
#
# Release build for Linux x86_64: one AppImage per renderer, via linuxdeployqt.
#
# Qt is linked dynamically here on purpose -- the AppImage bundles the Qt
# libraries it actually needs, and a shared build keeps compatibility with a
# wider range of distributions (see BUILD.md).
#
# Usage: ./build-linux.sh [clean] [mcp]
#
#   mcp   build with the MCP server (-DENABLE_MCP=ON). Only the OpenGL renderer
#         supports it in a windowed build, so the others are skipped. The console
#         build is not packaged here; configure it by hand with
#         -DENABLE_GUI=OFF -DENABLE_HEADLESS=ON, see MCP.md

set -euo pipefail

ARCHITECTURE="x86_64"
PLATFORM="linux"
QT_PATH="${HOME}/Qt/6.8.2/gcc_64"
LINUXDEPLOYQT="${HOME}/Downloads/linuxdeployqt-continuous-x86_64.AppImage"

# SDL2 is not built here: the AppImage would have to carry libSDL2, and the Qt
# and OpenGL renderers already cover this platform.
RENDERERS=("qt" "opengl")

ENABLE_MCP="OFF"
for arg in "$@"; do
    if [ "${arg}" = "mcp" ]; then ENABLE_MCP="ON"; fi
done

cd "$(dirname "$0")"
BUILD_ROOT="$(pwd)"

if [ ! -x "${LINUXDEPLOYQT}" ]; then
    echo "ERROR: linuxdeployqt not found or not executable: ${LINUXDEPLOYQT}" >&2
    exit 1
fi

if [ ! -d "${QT_PATH}" ]; then
    echo "ERROR: Qt not found at ${QT_PATH}" >&2
    exit 1
fi

# The VERSION file at the repository root is the single source of truth for the
# version: CMakeLists.txt reads the same file. globals.h carries the same number
# but is generated by cmake, so it is only in sync after a configure run.
APP_VERSION=$(tr -d ' \r\n' < ../VERSION)
if [ -z "${APP_VERSION}" ]; then
    echo "ERROR: cannot read the project version from ../VERSION" >&2
    exit 1
fi

echo "Building eCat3 ${APP_VERSION} for ${PLATFORM} ${ARCHITECTURE}"
mkdir -p release

for RENDERER in "${RENDERERS[@]}"; do
    echo
    echo "=== Renderer: ${RENDERER}"

    # A windowed MCP build is only supported on OpenGL, see MCP.md
    if [ "${ENABLE_MCP}" = "ON" ] && [ "${RENDERER}" != "opengl" ]; then
        echo "=== Skipping ${RENDERER}: an MCP build needs the OpenGL renderer"
        continue
    fi

    BUILD_DIR="${BUILD_ROOT}/build/${PLATFORM}-${ARCHITECTURE}-${RENDERER}"
    RELEASE_NAME="ecat-${APP_VERSION}-${PLATFORM}-${ARCHITECTURE}-${RENDERER}"
    if [ "${ENABLE_MCP}" = "ON" ]; then RELEASE_NAME="${RELEASE_NAME}-mcp"; fi
    RELEASE_DIR="${BUILD_ROOT}/release/${RELEASE_NAME}.AppDir"
    RESOURCES="${RELEASE_DIR}/usr/share/ecat"

    if [ "${1:-}" = "clean" ]; then
        rm -rf "${BUILD_DIR}"
    fi

    # Always reconfigure and rebuild: cmake and ninja work out what actually
    # changed, and a stale executable never reaches the AppImage.
    cmake -S ../src -B "${BUILD_DIR}" -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="${QT_PATH}" \
        -DRENDERER_${RENDERER^^}=1 \
        -DENABLE_MCP=${ENABLE_MCP}
    cmake --build "${BUILD_DIR}"

    # The on-screen keyboard is compiled in only when Qt has the Svg module;
    # linuxdeployqt then picks libQt6Svg up by itself
    if ! grep -q HAVE_QT_SVG "${BUILD_DIR}/build.ninja"; then
        echo "WARNING: no Qt Svg in ${QT_PATH}: the on-screen keyboard is left out of this build" >&2
    fi

    # The AppDir is recreated from scratch, otherwise leftovers from an earlier
    # build (configs of a machine that was renamed, say) end up in the AppImage.
    rm -rf "${RELEASE_DIR}"
    mkdir -p "${RELEASE_DIR}/usr/bin" "${RESOURCES}"
    cp -r ./.linux/ecat3.AppDir/* "${RELEASE_DIR}"
    cp "${BUILD_DIR}/eCat3" "${RELEASE_DIR}/usr/bin/"

    # deploy/ecat.ini is the developer's own working copy and must not be
    # released -- the distributed defaults live in deploy/.ecat.ini.
    cp -r ../deploy/* "${RESOURCES}"
    rm -f "${RESOURCES}/ecat.ini"
    cp ../deploy/.ecat.ini "${RESOURCES}/ecat.ini"

    (
        cd release
        # linuxdeployqt names the image after the .desktop entry and $VERSION.
        export VERSION="${APP_VERSION}-${PLATFORM}-${RENDERER}"
        rm -f "eCat3-${VERSION}-${ARCHITECTURE}.AppImage" "${RELEASE_NAME}.AppImage"
        "${LINUXDEPLOYQT}" \
            "${RELEASE_DIR}/usr/share/applications/ecat3.desktop" \
            -verbose=1 \
            -appimage \
            -no-translations \
            -no-copy-copyright-files \
            -qmake="${QT_PATH}/bin/qmake"
        mv "eCat3-${VERSION}-${ARCHITECTURE}.AppImage" "${RELEASE_NAME}.AppImage"
    )
done

echo
echo "=== Release contents:"
ls -l release/*.AppImage
