#!/bin/bash
#
# Browser, canvas. Same output as build-wasm.cmd.
#
# This produces NOT a desktop release but a deployment package: a directory of
# static files that goes into a web root as is, plus the same directory zipped.
# Machine configs, ROMs and disk images from deploy/ are packed into per-machine
# .bundle archives by src/wasm/package_machines.py -- the page fetches only the
# bundle of the machine the user picked.
#
# Needs Emscripten in PATH (`source emsdk_env.sh`).
#
# Usage: ./build-wasm.sh [clean]

set -euo pipefail

PLATFORM="web"

cd "$(dirname "$0")"

if ! command -v emcmake >/dev/null 2>&1; then
    echo "ERROR: emcmake not found. Install and activate the Emscripten SDK:" >&2
    echo "  git clone https://github.com/emscripten-core/emsdk.git" >&2
    echo "  cd emsdk && ./emsdk install latest && ./emsdk activate latest" >&2
    echo "  source ./emsdk_env.sh" >&2
    exit 1
fi

# emsdk exports EMSDK_PYTHON; fall back to whatever is on PATH.
PYTHON="${EMSDK_PYTHON:-}"
if [ -z "${PYTHON}" ]; then
    PYTHON=$(command -v python3 || command -v python) || {
        echo "ERROR: python not found; package_machines.py needs it." >&2
        exit 1
    }
fi

# The project() call in src/CMakeLists.txt is the single source of truth for the
# version. globals.h carries the same number but is generated by cmake, so it is
# only in sync after a configure run.
VERSION=$(sed -n 's/^project(.* VERSION \([0-9.]*\).*/\1/p' ../src/CMakeLists.txt)
if [ -z "${VERSION}" ]; then
    echo "ERROR: cannot read the project version from ../src/CMakeLists.txt" >&2
    exit 1
fi

BUILD_DIR="./build/${PLATFORM}"
RELEASE_NAME="ecat-${VERSION}-${PLATFORM}"
RELEASE_DIR="./release/${RELEASE_NAME}"

echo "Building eCat3 ${VERSION} for the browser (Emscripten)"

if [ "${1:-}" = "clean" ]; then
    rm -rf "${BUILD_DIR}"
fi

# Always reconfigure and rebuild: cmake and ninja work out what actually
# changed, so a stale module never reaches the package.
emcmake cmake -S ../src/wasm -B "${BUILD_DIR}" -G Ninja -DCMAKE_BUILD_TYPE=Release
cmake --build "${BUILD_DIR}"

# The package is recreated from scratch, otherwise leftovers from an earlier
# build (a bundle of a machine that was renamed, say) end up on the server.
rm -rf "${RELEASE_DIR}"
mkdir -p "${RELEASE_DIR}"

# The emulator itself.
cp "${BUILD_DIR}/ecat3.js"   "${RELEASE_DIR}/"
cp "${BUILD_DIR}/ecat3.wasm" "${RELEASE_DIR}/"
# Older Emscripten pthread builds emit a separate worker; newer ones inline it.
[ -f "${BUILD_DIR}/ecat3.worker.js" ] && cp "${BUILD_DIR}/ecat3.worker.js" "${RELEASE_DIR}/"

# The page.
cp ../src/wasm/shell.html   "${RELEASE_DIR}/index.html"
cp ../src/wasm/ecat_wasm.js "${RELEASE_DIR}/"

# Machine configs, ROMs and disk images, one .bundle per machine plus
# machines.json listing them for the page.
"${PYTHON}" ../src/wasm/package_machines.py ../deploy "${RELEASE_DIR}"

# How to put this on a server.
cp web/README.md          "${RELEASE_DIR}/"
cp web/nginx.conf.example "${RELEASE_DIR}/"
cp ../deploy/LICENSE.TXT   "${RELEASE_DIR}/"
cp ../deploy/COPYRIGHT.TXT "${RELEASE_DIR}/"

rm -f "./release/${RELEASE_NAME}.zip"
if command -v zip >/dev/null 2>&1; then
    (cd "${RELEASE_DIR}" && zip -q -9 -r "../${RELEASE_NAME}.zip" .)
else
    echo "ERROR: zip not found; install the zip package." >&2
    exit 1
fi

echo
echo "=== Release contents:"
ls -l "${RELEASE_DIR}"
echo
echo "  release/${RELEASE_NAME}.zip"
echo "  release/${RELEASE_NAME}/  — goes into a web root as is"
echo
echo "Serving it from the file system will not work: the page needs"
echo "COOP/COEP headers for SharedArrayBuffer. For a local try:"
echo "  ${PYTHON} ../src/wasm/serve_wasm.py ${RELEASE_DIR}"
echo
