#!/bin/bash
#
# Release build for macOS: one universal (x86_64 + arm64) .dmg per renderer.
#
# Qt is linked statically (see BUILD.md and macos_build_qt_universal.sh), so the
# bundle carries no Qt frameworks. Only SDL2, when the binary actually links
# against it, is copied into Contents/Frameworks.
#
# Usage: ./build-macos.sh [clean]

set -euo pipefail

QT_PATH="${HOME}/Qt-6.8.2-static-universal"

PLATFORM="macos"
ARCHITECTURE="universal"
APP_NAME="eCat3"

# SDL2 is not built here: the Qt and OpenGL renderers already cover this
# platform and the SDL2 one would add a dylib to every bundle.
RENDERERS=("qt" "opengl")

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
RELEASE_DIR="${SCRIPT_DIR}/release"

if [ ! -d "${QT_PATH}" ]; then
    echo "ERROR: Qt not found at ${QT_PATH}" >&2
    exit 1
fi

# The VERSION file at the repository root is the single source of truth for the
# version: CMakeLists.txt reads the same file. globals.h carries the same number
# but is generated by cmake, so it is only in sync after a configure run.
APP_VERSION=$(tr -d ' \r\n' < "${REPO_DIR}/VERSION")
if [ -z "${APP_VERSION}" ]; then
    echo "ERROR: cannot read the project version from ${REPO_DIR}/VERSION" >&2
    exit 1
fi

echo "Building ${APP_NAME} ${APP_VERSION} for ${PLATFORM} ${ARCHITECTURE}"
mkdir -p "${RELEASE_DIR}"

for RENDERER in "${RENDERERS[@]}"; do
  echo
  echo "=== Renderer: ${RENDERER}"

  BUILD_DIR="${SCRIPT_DIR}/build/${PLATFORM}-${ARCHITECTURE}-${RENDERER}"
  RENDERER_UPPER=$(echo "${RENDERER}" | tr '[:lower:]' '[:upper:]')
  DMG_NAME="ecat-${APP_VERSION}-${PLATFORM}-${ARCHITECTURE}-${RENDERER}.dmg"

  if [ "${1:-}" = "clean" ]; then
      rm -rf "${BUILD_DIR}"
  fi

  # Always reconfigure and rebuild: cmake and ninja work out what actually
  # changed, and a stale executable never reaches the .dmg.
  cmake -S "${REPO_DIR}/src" -B "${BUILD_DIR}" -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="${QT_PATH}" \
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
        -DRENDERER_${RENDERER_UPPER}=1
  cmake --build "${BUILD_DIR}"

  # Copy deploy data into the app bundle Resources. The payload directories are
  # dropped first, otherwise leftovers from an earlier build (configs of a
  # machine that was renamed, say) stay in the bundle. Resources itself is not
  # wiped -- it also holds the icon put there by cmake.
  RESOURCES="${BUILD_DIR}/${APP_NAME}.app/Contents/Resources"
  rm -rf "${RESOURCES}/computers" "${RESOURCES}/data" "${RESOURCES}/software"
  cp -r "${REPO_DIR}/deploy/" "${RESOURCES}"
  # deploy/ecat.ini is the developer's own working copy and must not be
  # released -- the distributed defaults live in deploy/.ecat.ini.
  rm -f "${RESOURCES}/ecat.ini" "${RESOURCES}/.ecat.ini"
  cp "${REPO_DIR}/deploy/.ecat.ini" "${RESOURCES}/ecat.ini"

  # Bundle SDL2 dylib
  APP_BINARY="${BUILD_DIR}/${APP_NAME}.app/Contents/MacOS/${APP_NAME}"
  FRAMEWORKS_DIR="${BUILD_DIR}/${APP_NAME}.app/Contents/Frameworks"
  SDL2_LIB=$(otool -L "${APP_BINARY}" | grep libSDL2 | awk '{print $1}' || true)
  if [ -n "${SDL2_LIB}" ]; then
    mkdir -p "${FRAMEWORKS_DIR}"
    cp "${SDL2_LIB}" "${FRAMEWORKS_DIR}/"
    install_name_tool -change "${SDL2_LIB}" \
        "@executable_path/../Frameworks/$(basename "${SDL2_LIB}")" \
        "${APP_BINARY}"
  fi

  # hdiutil refuses to overwrite an existing image, and a stale .dmg here would
  # silently be shipped as the new release.
  rm -f "${RELEASE_DIR}/${DMG_NAME}"
  hdiutil create -volname "${APP_NAME}" \
      -srcfolder "${BUILD_DIR}/${APP_NAME}.app" \
      -ov -format UDZO \
      "${RELEASE_DIR}/${DMG_NAME}"
done

echo
echo "=== Release contents:"
ls -l "${RELEASE_DIR}"/*.dmg
