#!/bin/bash
#
# Release build for Linux x86_64, one archive per variant:
#
#   opengl       the windowed emulator, an AppImage each (via linuxdeployqt)
#   opengl-mcp   the same with the MCP server (-DENABLE_MCP=ON); a windowed MCP
#                build needs the OpenGL renderer
#   headless     the console executable with the MCP server, no Qt at all, a
#                .tar.gz: bin/eCat3-headless next to share/ecat/, which is where
#                the console build looks for its machines
#   qt           the windowed emulator on the Qt renderer, only with "all"
#
# Qt is linked dynamically here on purpose -- the AppImage bundles the Qt
# libraries it actually needs, and a shared build keeps compatibility with a
# wider range of distributions (see docs/BUILD.md).
#
# Usage: ./build-linux.sh [clean] [all]

set -euo pipefail

ARCHITECTURE="x86_64"
PLATFORM="linux"
QT_PATH="${HOME}/Qt/6.8.2/gcc_64"
LINUXDEPLOYQT="${HOME}/Downloads/linuxdeployqt-continuous-x86_64.AppImage"

# SDL2 is not built here: the AppImage would have to carry libSDL2, and the Qt
# and OpenGL renderers already cover this platform.
VARIANTS=("opengl" "opengl-mcp" "headless")

CLEAN=0
for arg in "$@"; do
    if [ "${arg}" = "clean" ]; then CLEAN=1; fi
    if [ "${arg}" = "all" ]; then VARIANTS=("qt" "${VARIANTS[@]}"); fi
done

cd "$(dirname "$0")"
BUILD_ROOT="$(pwd)"

if [ ! -x "${LINUXDEPLOYQT}" ]; then
    echo "ERROR: linuxdeployqt not found or not executable: ${LINUXDEPLOYQT}" >&2
    exit 1
fi

if [ ! -d "${QT_PATH}" ]; then
    echo "ERROR: Qt not found at ${QT_PATH}" >&2
    exit 1
fi

# The VERSION file at the repository root is the single source of truth for the
# version: CMakeLists.txt reads the same file. globals.h carries the same number
# but is generated by cmake, so it is only in sync after a configure run.
APP_VERSION=$(tr -d ' \r\n' < ../VERSION)
if [ -z "${APP_VERSION}" ]; then
    echo "ERROR: cannot read the project version from ../VERSION" >&2
    exit 1
fi

# Copies deploy/ into $1, with the distributed defaults as ecat.ini:
# deploy/ecat.ini is the developer's own working copy and must not be released,
# and neither are deploy/ecat-exts and deploy/scripts
copy_deploy() {
    cp -r ../deploy/. "$1"
    rm -rf "$1/ecat-exts" "$1/scripts"
    rm -f "$1/ecat.ini" "$1/.ecat.ini"
    cp ../deploy/.ecat.ini "$1/ecat.ini"
}

echo "Building eCat3 ${APP_VERSION} for ${PLATFORM} ${ARCHITECTURE}"
mkdir -p release

for VARIANT in "${VARIANTS[@]}"; do
    echo
    echo "=== Variant: ${VARIANT}"

    BUILD_DIR="${BUILD_ROOT}/build/${PLATFORM}-${ARCHITECTURE}-${VARIANT}"
    RELEASE_NAME="ecat-${APP_VERSION}-${PLATFORM}-${ARCHITECTURE}-${VARIANT}"

    case "${VARIANT}" in
        headless)   FLAGS=(-DENABLE_GUI=OFF -DENABLE_HEADLESS=ON -DENABLE_MCP=ON) ;;
        opengl-mcp) FLAGS=(-DRENDERER_OPENGL=1 -DENABLE_MCP=ON) ;;
        *)          FLAGS=(-DRENDERER_${VARIANT^^}=1 -DENABLE_MCP=OFF) ;;
    esac

    if [ "${CLEAN}" = "1" ]; then
        rm -rf "${BUILD_DIR}"
    fi

    # Always reconfigure and rebuild: cmake and ninja work out what actually
    # changed, and a stale executable never reaches the release.
    cmake -S ../src -B "${BUILD_DIR}" -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="${QT_PATH}" \
        "${FLAGS[@]}"
    cmake --build "${BUILD_DIR}"

    if [ "${VARIANT}" = "headless" ]; then
        # A console program gains nothing from an AppImage. The layout is the
        # one resolve_paths() in src/headless/headless_main.cpp falls back to
        # when the working directory holds no computers/: <bin>/../share/ecat
        STAGING="${BUILD_DIR}/pkg/${RELEASE_NAME}"
        rm -rf "${BUILD_DIR}/pkg"
        mkdir -p "${STAGING}/bin" "${STAGING}/share/ecat"
        cp "${BUILD_DIR}/eCat3-headless" "${STAGING}/bin/"
        copy_deploy "${STAGING}/share/ecat"
        rm -f "release/${RELEASE_NAME}.tar.gz"
        tar -czf "release/${RELEASE_NAME}.tar.gz" -C "${BUILD_DIR}/pkg" "${RELEASE_NAME}"
        continue
    fi

    RELEASE_DIR="${BUILD_ROOT}/release/${RELEASE_NAME}.AppDir"
    RESOURCES="${RELEASE_DIR}/usr/share/ecat"

    # The on-screen keyboard is compiled in only when Qt has the Svg module;
    # linuxdeployqt then picks libQt6Svg up by itself
    if ! grep -q HAVE_QT_SVG "${BUILD_DIR}/build.ninja"; then
        echo "WARNING: no Qt Svg in ${QT_PATH}: the on-screen keyboard is left out of this build" >&2
    fi

    # The AppDir is recreated from scratch, otherwise leftovers from an earlier
    # build (configs of a machine that was renamed, say) end up in the AppImage.
    rm -rf "${RELEASE_DIR}"
    mkdir -p "${RELEASE_DIR}/usr/bin" "${RESOURCES}"
    cp -r ./.linux/ecat3.AppDir/* "${RELEASE_DIR}"
    cp "${BUILD_DIR}/eCat3" "${RELEASE_DIR}/usr/bin/"
    copy_deploy "${RESOURCES}"

    (
        cd release
        # linuxdeployqt names the image after the .desktop entry and $VERSION.
        export VERSION="${APP_VERSION}-${PLATFORM}-${VARIANT}"
        rm -f "eCat3-${VERSION}-${ARCHITECTURE}.AppImage" "${RELEASE_NAME}.AppImage"
        "${LINUXDEPLOYQT}" \
            "${RELEASE_DIR}/usr/share/applications/ecat3.desktop" \
            -verbose=1 \
            -appimage \
            -no-translations \
            -no-copy-copyright-files \
            -qmake="${QT_PATH}/bin/qmake"
        mv "eCat3-${VERSION}-${ARCHITECTURE}.AppImage" "${RELEASE_NAME}.AppImage"
    )
done

echo
echo "=== Release contents:"
ls -l release/*-${PLATFORM}-*.AppImage release/*-${PLATFORM}-*.tar.gz
