#!/bin/bash
#
# Release build for macOS: universal (x86_64 + arm64) binaries, one archive per
# variant:
#
#   qt, opengl   the windowed emulator, a .dmg each
#   opengl-mcp   the same with the MCP server (-DENABLE_MCP=ON), a .dmg; a
#                windowed MCP build needs the OpenGL renderer
#   headless     the console executable with the MCP server, no Qt at all, a
#                .tar.gz: bin/eCat3-headless next to share/ecat/, which is where
#                the console build looks for its machines
#
# Qt is linked statically (see docs/BUILD.md and macos_build_qt_universal.sh), so the
# bundle carries no Qt frameworks. Only SDL2, when the binary actually links
# against it, is copied into Contents/Frameworks.
#
# Usage: ./build-macos.sh [clean]

set -euo pipefail

QT_PATH="${HOME}/Qt-6.8.2-static-universal"

PLATFORM="macos"
ARCHITECTURE="universal"
APP_NAME="eCat3"

# SDL2 is not built here: the Qt and OpenGL renderers already cover this
# platform and the SDL2 one would add a dylib to every bundle.
VARIANTS=("qt" "opengl" "opengl-mcp" "headless")

CLEAN=0
for arg in "$@"; do
    if [ "${arg}" = "clean" ]; then CLEAN=1; fi
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
RELEASE_DIR="${SCRIPT_DIR}/release"

if [ ! -d "${QT_PATH}" ]; then
    echo "ERROR: Qt not found at ${QT_PATH}" >&2
    exit 1
fi

# The VERSION file at the repository root is the single source of truth for the
# version: CMakeLists.txt reads the same file. globals.h carries the same number
# but is generated by cmake, so it is only in sync after a configure run.
APP_VERSION=$(tr -d ' \r\n' < "${REPO_DIR}/VERSION")
if [ -z "${APP_VERSION}" ]; then
    echo "ERROR: cannot read the project version from ${REPO_DIR}/VERSION" >&2
    exit 1
fi

# Copies deploy/ into $1, with the distributed defaults as ecat.ini:
# deploy/ecat.ini is the developer's own working copy and must not be released,
# and neither are deploy/ecat-exts and deploy/scripts
copy_deploy() {
    cp -r "${REPO_DIR}/deploy/" "$1"
    rm -rf "$1/ecat-exts" "$1/scripts"
    rm -f "$1/ecat.ini" "$1/.ecat.ini"
    cp "${REPO_DIR}/deploy/.ecat.ini" "$1/ecat.ini"
}

echo "Building ${APP_NAME} ${APP_VERSION} for ${PLATFORM} ${ARCHITECTURE}"
mkdir -p "${RELEASE_DIR}"

for VARIANT in "${VARIANTS[@]}"; do
  echo
  echo "=== Variant: ${VARIANT}"

  BUILD_DIR="${SCRIPT_DIR}/build/${PLATFORM}-${ARCHITECTURE}-${VARIANT}"
  RELEASE_NAME="ecat-${APP_VERSION}-${PLATFORM}-${ARCHITECTURE}-${VARIANT}"

  case "${VARIANT}" in
      headless)   FLAGS=(-DENABLE_GUI=OFF -DENABLE_HEADLESS=ON -DENABLE_MCP=ON) ;;
      opengl-mcp) FLAGS=(-DRENDERER_OPENGL=1 -DENABLE_MCP=ON) ;;
      *)          FLAGS=(-DRENDERER_$(echo "${VARIANT}" | tr '[:lower:]' '[:upper:]')=1 -DENABLE_MCP=OFF) ;;
  esac

  if [ "${CLEAN}" = "1" ]; then
      rm -rf "${BUILD_DIR}"
  fi

  # Always reconfigure and rebuild: cmake and ninja work out what actually
  # changed, and a stale executable never reaches the release.
  cmake -S "${REPO_DIR}/src" -B "${BUILD_DIR}" -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="${QT_PATH}" \
        -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
        "${FLAGS[@]}"
  cmake --build "${BUILD_DIR}"

  if [ "${VARIANT}" = "headless" ]; then
      # A console program gains nothing from a bundle or a .dmg. The layout is
      # the one resolve_paths() in src/headless/headless_main.cpp falls back to
      # when the working directory holds no computers/: <bin>/../share/ecat
      STAGING="${BUILD_DIR}/pkg/${RELEASE_NAME}"
      rm -rf "${BUILD_DIR}/pkg"
      mkdir -p "${STAGING}/bin" "${STAGING}/share/ecat"
      cp "${BUILD_DIR}/${APP_NAME}-headless" "${STAGING}/bin/"
      copy_deploy "${STAGING}/share/ecat"
      rm -f "${RELEASE_DIR}/${RELEASE_NAME}.tar.gz"
      tar -czf "${RELEASE_DIR}/${RELEASE_NAME}.tar.gz" -C "${BUILD_DIR}/pkg" "${RELEASE_NAME}"
      continue
  fi

  # The on-screen keyboard is compiled in only when Qt has the Svg module,
  # which a static Qt links into the binary itself
  if ! grep -q HAVE_QT_SVG "${BUILD_DIR}/build.ninja"; then
      echo "WARNING: no Qt Svg in ${QT_PATH}: the on-screen keyboard is left out of this build" >&2
  fi

  # Copy deploy data into the app bundle Resources. The payload directories are
  # dropped first, otherwise leftovers from an earlier build (configs of a
  # machine that was renamed, say) stay in the bundle. Resources itself is not
  # wiped -- it also holds the icon put there by cmake.
  RESOURCES="${BUILD_DIR}/${APP_NAME}.app/Contents/Resources"
  rm -rf "${RESOURCES}/computers" "${RESOURCES}/data" "${RESOURCES}/software"
  copy_deploy "${RESOURCES}"

  # Bundle SDL2 dylib
  APP_BINARY="${BUILD_DIR}/${APP_NAME}.app/Contents/MacOS/${APP_NAME}"
  FRAMEWORKS_DIR="${BUILD_DIR}/${APP_NAME}.app/Contents/Frameworks"
  SDL2_LIB=$(otool -L "${APP_BINARY}" | grep libSDL2 | awk '{print $1}' || true)
  if [ -n "${SDL2_LIB}" ]; then
    mkdir -p "${FRAMEWORKS_DIR}"
    cp "${SDL2_LIB}" "${FRAMEWORKS_DIR}/"
    install_name_tool -change "${SDL2_LIB}" \
        "@executable_path/../Frameworks/$(basename "${SDL2_LIB}")" \
        "${APP_BINARY}"
  fi

  # The volume shows the bundle next to a link to /Applications, so installing is
  # a drag, and a visible copy of software/. The copy inside the bundle stays: the
  # configs resolve their images from there. A file dialog does not enter a
  # bundle, so without the visible copy the images are out of reach once the user
  # leaves the folder the first dialog opens in.
  STAGING="${BUILD_DIR}/dmg"
  rm -rf "${STAGING}"
  mkdir -p "${STAGING}"
  ditto "${BUILD_DIR}/${APP_NAME}.app" "${STAGING}/${APP_NAME}.app"
  ln -s /Applications "${STAGING}/Applications"
  ditto "${REPO_DIR}/deploy/software" "${STAGING}/software"

  # hdiutil refuses to overwrite an existing image, and a stale .dmg here would
  # silently be shipped as the new release.
  rm -f "${RELEASE_DIR}/${RELEASE_NAME}.dmg"
  hdiutil create -volname "${APP_NAME}" \
      -srcfolder "${STAGING}" \
      -ov -format UDZO \
      "${RELEASE_DIR}/${RELEASE_NAME}.dmg"
done

echo
echo "=== Release contents:"
ls -l "${RELEASE_DIR}"/*-${PLATFORM}-*.dmg "${RELEASE_DIR}"/*-${PLATFORM}-*.tar.gz
