@echo off

SET _ROOT_QT=C:\DEV\Qt
SET _QT_VERSION=6.8.1
SET _MINGW_VERSION=mingw1310_64

SET _ROOT_CMAKE=%_ROOT_QT%\Tools\CMake_64\bin
SET _ROOT_NINJA=%_ROOT_QT%\Tools\Ninja
SET _ROOT_MINGW=%_ROOT_QT%\Tools\%_MINGW_VERSION%\bin
SET _ROOT_BIN=%_ROOT_QT%\%_QT_VERSION%\mingw_64\bin
SET _ROOT_SRC=%_ROOT_QT%\%_QT_VERSION%\Src

SET PATH=%_ROOT_CMAKE%;%_ROOT_NINJA%;%_ROOT_MINGW%;%_ROOT_BIN%;%_ROOT_SRC%;%PATH%
