@echo off

SET _ROOT_QT=C:\DEV\Qt
SET _QT_VERSION=5.6.3
SET _MINGW_VERSION=mingw492_32

SET _ROOT_CMAKE=%_ROOT_QT%\Tools\CMake_64\bin
SET _ROOT_NINJA=%_ROOT_QT%\Tools\Ninja
SET _ROOT_MINGW=%_ROOT_QT%\Tools\%_MINGW_VERSION%\bin
SET _QT_PATH=%_ROOT_QT%\%_QT_VERSION%\mingw492_32
SET _ROOT_BIN=%_QT_PATH%\bin
SET _ROOT_SRC=%_ROOT_QT%\%_QT_VERSION%\Src

SET SDL2_ROOT=C:\DEV\SDL2-2.32.10\i686-w64-mingw32
SET SDL2_BIN=%SDL2_ROOT%\bin

SET PATH=%_ROOT_CMAKE%;%_ROOT_NINJA%;%_ROOT_MINGW%;%_ROOT_BIN%;%_ROOT_SRC%;%PATH%
