@ECHO OFF
REM ---------------------------------------------------------------------------
REM Shared subroutines for the Windows release scripts.
REM
REM   call win-common.cmd find7z             -- locate 7-Zip, path lands in %SEVENZIP%
REM   call win-common.cmd version <version file> -- project version lands in %_VERSION%
REM   call win-common.cmd reset <dir>        -- (re)create an empty directory
REM   call win-common.cmd deploy <dir>       -- copy ..\deploy payload into <dir>
REM   call win-common.cmd zip <dir> <name>   -- pack the CONTENTS of <dir> into <dir>\..\<name>.zip
REM   call win-common.cmd report <dir>       -- print the size of every file in <dir>
REM   call win-common.cmd checkgen <dir> <g> -- drop <dir> if it was configured
REM                                             with a generator other than <g>
REM ---------------------------------------------------------------------------

if /I "%~1"=="find7z"   goto :find7z
if /I "%~1"=="version"  goto :version
if /I "%~1"=="reset"    goto :reset
if /I "%~1"=="deploy"   goto :deploy
if /I "%~1"=="zip"      goto :zip
if /I "%~1"=="report"   goto :report
if /I "%~1"=="checkgen" goto :checkgen

echo win-common.cmd: unknown command "%~1"
exit /b 1

REM ---------------------------------------------------------------------------
:find7z
if defined SEVENZIP exit /b 0
where 7z >nul 2>&1
if not errorlevel 1 (
    set "SEVENZIP=7z"
    exit /b 0
)
if exist "%ProgramFiles%\7-Zip\7z.exe" (
    set "SEVENZIP=%ProgramFiles%\7-Zip\7z.exe"
    exit /b 0
)
if exist "%ProgramFiles(x86)%\7-Zip\7z.exe" (
    set "SEVENZIP=%ProgramFiles(x86)%\7-Zip\7z.exe"
    exit /b 0
)
echo ERROR: 7z.exe not found. Please install 7-Zip or add it to PATH.
exit /b 1

REM ---------------------------------------------------------------------------
REM The version is read from the VERSION file at the repository root, which is
REM the single source of truth: CMakeLists.txt takes the number from there too.
REM globals.h carries the same number but is generated by configure_file(), so
REM it is only in sync after a cmake run.
:version
set "_VERSION="
if not exist "%~2" (
    echo ERROR: version file "%~2" not found.
    exit /b 1
)
set /p _VERSION=<"%~2"
if not defined _VERSION (
    echo ERROR: cannot read the project version from "%~2".
    exit /b 1
)
exit /b 0

REM ---------------------------------------------------------------------------
REM The release directory is recreated from scratch, otherwise leftovers from
REM an earlier build (say, DLLs that are no longer needed, or config files of a
REM machine that was renamed) end up in the archive.
:reset
if exist "%~2" rmdir /s /q "%~2" || exit /b 1
mkdir "%~2" || exit /b 1
exit /b 0

REM ---------------------------------------------------------------------------
REM deploy\ holds the machine configs, ROMs and software shipped with the
REM emulator. deploy\ecat.ini is the developer's own working copy and must not
REM be released -- the distributed defaults live in deploy\.ecat.ini.
:deploy
xcopy "%~dp0..\deploy\*" "%~2\" /E /I /Y /Q >nul || exit /b 1
if exist "%~2\ecat.ini" del /q "%~2\ecat.ini"
if exist "%~2\.ecat.ini" del /q "%~2\.ecat.ini"
copy /y "%~dp0..\deploy\.ecat.ini" "%~2\ecat.ini" >nul || exit /b 1
exit /b 0

REM ---------------------------------------------------------------------------
:zip
call "%~dp0win-common.cmd" find7z || exit /b 1
if exist "%~2\..\%~3.zip" del /q "%~2\..\%~3.zip"
pushd "%~2" || exit /b 1
"%SEVENZIP%" a "..\%~3.zip" * -mx9 >nul || (popd & exit /b 1)
popd
echo Packed: %~2\..\%~3.zip
exit /b 0

REM ---------------------------------------------------------------------------
:report
echo.
echo === Release contents: %~2
for /r "%~2" %%F in (*) do @echo    %%~zF  %%~nxF
echo.
exit /b 0

REM ---------------------------------------------------------------------------
REM cmake refuses to reuse a build directory configured with another generator,
REM and the error is easy to miss in a long build log. Drop the stale cache so
REM the release scripts keep working after the generator changes.
:checkgen
if not exist "%~2\CMakeCache.txt" exit /b 0
findstr /X /C:"CMAKE_GENERATOR:INTERNAL=%~3" "%~2\CMakeCache.txt" >nul && exit /b 0
echo Build directory was configured with a different generator, reconfiguring from scratch.
rmdir /s /q "%~2" || exit /b 1
exit /b 0
