# table.pkl -> vm2_timing_table.inc (раскладка Vm1BusTiming::F_* с формами EIS)
import pickle, sys

table = pickle.load(open('table.pkl', 'rb'))

F_DOUBLE = 0
F_SINGLE = F_DOUBLE + 12 * 256
F_EIS = F_SINGLE + 28 * 16
F_XOR = F_EIS + 5 * 16
F_JMP = F_XOR + 16
F_JSR = F_JMP + 16
F_RTS = F_JSR + 16
names = ['RTS', 'RTI', 'RTT', 'TRAP', 'MARK', 'CC_CLEAR', 'CC_SET', 'BR_TAKEN', 'BR_NOT',
         'SOB_TAKEN', 'SOB_NOT', 'INTERRUPT', 'INTERRUPT_VIRQ', 'WAIT', 'RESET']
F = {n: F_RTS + i for i, n in enumerate(names)}
F_COUNT = F_RTS + len(names)

forms = [None] * F_COUNT
origin = [''] * F_COUNT
approx = []

def put(idx, key, how='sim'):
    forms[idx] = table[key]; origin[idx] = '%s %s' % (how, key)

for key in table:
    k0 = key[0]
    if k0 == 'D': put(F_DOUBLE + key[1] * 256 + key[2] * 16 + key[3], key)
    elif k0 == 'S': put(F_SINGLE + key[1] * 16 + key[2], key)
    elif k0 == 'E': put(F_EIS + key[1] * 16 + key[2], key)
    elif k0 == 'XOR': put(F_XOR + key[1], key)
    elif k0 == 'JMP': put(F_JMP + key[1], key)
    elif k0 == 'JSR': put(F_JSR + key[1], key)
    elif k0 == 'RTS': put(F['RTS'], key)
    elif k0 == 'RTI': put(F['RTI'], key)
    elif k0 == 'RTT': put(F['RTT'], key)
    elif k0 == 'EMT': put(F['TRAP'], key)
    elif k0 == 'MARK': put(F['MARK'], key)
    elif k0 == 'CC': put(F['CC_SET'] if key[1] else F['CC_CLEAR'], key)
    elif k0 == 'BR': put(F['BR_TAKEN'] if key[1] else F['BR_NOT'], key)
    elif k0 == 'SOB': put(F['SOB_TAKEN'] if key[1] else F['SOB_NOT'], key)
    elif k0 == 'INT': put(F['INTERRUPT'], key)
    elif k0 == 'VINT': put(F['INTERRUPT_VIRQ'], key)

# формы, которых кристалл здесь не выполнял: ближайшая выполненная
def spec(m, pc): return m * 2 + pc
def fill(base, n_ops, fmt):
    for op in range(n_ops):
        for s in range(16):
            idx = base + fmt(op, s)
            if forms[idx] is None:
                m, pc = divmod(s, 2)
                alt = [spec(m, 0)] if pc else []
                if m == 1 and pc: alt.append(spec(2, 0))       # #n приёмником: (R)+
                alt += {1: [spec(2, 0)], 2: [spec(3, 0)], 4: [spec(5, 0)],
                        5: [spec(7, 0)], 0: [], 3: [], 6: [], 7: []}.get(m, [])
                for a in alt:
                    j = base + fmt(op, a)
                    if forms[j] is not None:
                        forms[idx] = forms[j]; origin[idx] = 'like ' + origin[j]
                        approx.append((idx, origin[idx])); break

def fill_double():
    # PC как обычный регистр (режимы 0, 1, 4, 5 с R7) идёт по микропрограмме
    # любого регистра: та же форма без признака PC
    for op in range(12):
        for s in range(16):
            for d in range(16):
                idx = F_DOUBLE + op * 256 + s * 16 + d
                if forms[idx] is not None: continue
                for s2, d2 in ((s, d & ~1), (s & ~1, d), (s & ~1, d & ~1), (s, spec(2, 0)), (s & ~1, spec(2, 0))):
                    j = F_DOUBLE + op * 256 + s2 * 16 + d2
                    if forms[j] is not None:
                        forms[idx] = forms[j]; origin[idx] = 'like ' + origin[j]; break

fill_double()
fill(F_SINGLE, 28, lambda op, s: op * 16 + s)
fill(F_EIS, 5, lambda op, s: op * 16 + s)
fill(F_XOR, 1, lambda op, s: s)
fill(F_JMP, 1, lambda op, s: s)
fill(F_JSR, 1, lambda op, s: s)
for base in (F_JMP, F_JSR):
    for s, like in ((spec(1, 0), spec(2, 0)), (spec(4, 0), spec(2, 0)), (spec(5, 0), spec(3, 0))):
        if forms[base + s] is None and forms[base + like] is not None:
            forms[base + s] = forms[base + like]; origin[base + s] = 'like ' + origin[base + like]

KIND = {'R': 'K_READ', 'W': 'K_WRITE', 'M': 'K_RMW'}
ROLE = {'D': 'R_DATA', 'I': 'R_STREAM', 'N': 'R_NONE', 'F': 'R_PREFETCH'}

steps_out = []; first = []; count = []; tail = []
dedup = {}
for i in range(F_COUNT):
    f = forms[i]
    if f is None:
        first.append(0); count.append(0); tail.append(0); continue
    t = tuple(tuple(s) for s in f['steps'])
    if t not in dedup:
        dedup[t] = len(steps_out)
        steps_out += list(t)
    first.append(dedup[t]); count.append(len(t)); tail.append(f['tail'])
assert max(tail) < 256 and all(0 <= s[2] < 256 and 0 <= s[3] < 256 and 0 <= s[4] < 256 for s in steps_out), 'не влезает в uint8_t'

missing = sum(1 for c in count if c == 0)
with open(sys.argv[1] if len(sys.argv) > 1 else 'vm2_timing_table.inc', 'w', newline='\n') as o:
    o.write('// Generated by tools/vm2-timing/emit_inc.py from a simulation of the К1801ВМ2\n')
    o.write('// (github 1801BM1/cpu11, synchronous model). Do not edit. Times in CLC clocks.\n')
    o.write('// %d forms, %d without a template (the old count is used for them)\n\n' % (F_COUNT, missing))
    o.write('static const Vm1BusTiming::Step VM2_STEPS[] = {\n')
    for s in steps_out:
        o.write('    { Vm1BusTiming::%s, Vm1BusTiming::%s, %d, %d, %d },\n' % (KIND[s[0]], ROLE[s[1]], s[2], s[3], s[4]))
    o.write('};\n\n')
    def arr(name, typ, vals):
        o.write('static const %s %s[Vm1BusTiming::F2_COUNT] = {\n' % (typ, name))
        for i in range(0, len(vals), 16):
            o.write('    ' + ', '.join(str(v) for v in vals[i:i + 16]) + ',\n')
        o.write('};\n\n')
    assert len(first) == F_COUNT
    arr('VM2_FIRST', 'uint16_t', first)
    arr('VM2_COUNT', 'uint8_t', count)
    arr('VM2_TAIL', 'uint8_t', tail)
print('forms', F_COUNT, 'steps', len(steps_out), 'missing', missing, 'approximated', len(approx))
for i, c in enumerate(count):
    if c == 0: print('  no template:', i)
