// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2023-2026 Mikhail Revzin <p3.141592653589793238462643@gmail.com>
// Part of the eCat3 project: https://github.com/Ptr314/ecat3
// Description: bus cycle timing of the К1801ВМ1 (timing = vm1)

#include "vm1_timing.h"
#include "emulator/core.h"

// Generated by tools/bk-timing/emit_inc.py from a simulation of the chip:
// VM1_STEPS, VM1_FIRST, VM1_COUNT and VM1_TAIL
#include "vm1_timing_table.inc"

Vm1BusTiming::Vm1BusTiming(unsigned int clock_hz)
    : m_clock_hz(clock_hz)
{
}

// A processor half clock after the strobe for a read, a full clock for a
// write: what the replica does with a memory that answers at once
static const int FAST_READ_HALVES = 1;
static const int FAST_WRITE_HALVES = 2;
// From RPLY to the release of the strobe
static const int RELEASE_HALVES = 3;

const Vm1BusTiming::ReplyTicks * Vm1BusTiming::ticks_of(const BusReply * reply)
{
    for (ReplyTicks & c : m_conv)
        if (c.reply == reply) return &c;
    for (ReplyTicks & c : m_conv)
        if (c.reply == nullptr) {
            //ns -> ticks, rounded to the nearest: 12 ticks a clock
            const uint64_t hz = (uint64_t)m_clock_hz * TICKS_PER_CLOCK;
            auto conv = [hz](unsigned int ns) {
                return (uint32_t)(((uint64_t)ns * hz + 500000000ull) / 1000000000ull);
            };
            c.reply = reply;
            c.window = conv(reply->window_ns);
            c.setup_read = conv(reply->setup_read_ns);
            c.setup_write = conv(reply->setup_write_ns);
            c.setup_rmw = conv(reply->setup_rmw_ns);
            c.delay = conv(reply->reply_ns);
            c.rmw_extra = reply->rmw_extra * TICKS_PER_HALF;
            return &c;
        }
    return nullptr;     // more reply kinds than a machine has ever had
}

uint32_t Vm1BusTiming::phase_of_start(uint32_t window)
{
    if (m_phase_window != window) {
        m_phase_window = window;
        m_phase = (uint32_t)(m_start % window);
    }
    return m_phase;
}

uint32_t Vm1BusTiming::reply_time(uint32_t strobe, uint8_t kind, bool rmw_write, const BusReply * reply)
{
    const ReplyTicks * r = (reply != nullptr) ? ticks_of(reply) : nullptr;
    if (r == nullptr || r->window == 0) {
        if (kind == K_READ) return strobe + FAST_READ_HALVES * TICKS_PER_HALF;
        return strobe + FAST_WRITE_HALVES * TICKS_PER_HALF + (rmw_write && r ? r->rmw_extra : 0);
    }
    const uint32_t setup = (kind == K_READ) ? r->setup_read : (rmw_write ? r->setup_rmw : r->setup_write);
    //The first point of the controller's cycle at or after the strobe plus its
    //setup; m_start sits at phase_of_start() within that cycle
    const uint32_t x = strobe + setup;
    const uint32_t into = (phase_of_start(r->window) + x) % r->window;
    const uint32_t point = x + (into ? r->window - into : 0);
    //The processor takes RPLY on its own clock edges; m_start is on one
    const uint32_t seen = point + r->delay;
    return (seen + TICKS_PER_HALF - 1) / TICKS_PER_HALF * TICKS_PER_HALF;
}

int Vm1BusTiming::finish(unsigned int form, const BusReply * prefetch_reply, bool skip_opcode)
{
    if (form >= F_COUNT || VM1_COUNT[form] == 0) {
        m_count = 0;
        return -1;
    }

    const Step * steps = &VM1_STEPS[VM1_FIRST[form]];
    const unsigned int n = VM1_COUNT[form];

    //Records are matched to the steps of their own role in order: the chip
    //and the emulator agree on the order of the data cycles and on the order
    //of the instruction stream words, not necessarily on how the two interleave
    unsigned int next_rec[2] = {0, 0};
    if (skip_opcode)
        while (next_rec[R_STREAM] < m_count && m_acc[next_rec[R_STREAM]++].role != R_STREAM) {}
    auto take = [this, &next_rec](uint8_t role, uint8_t kind) -> const BusReply * {
        if (role == R_NONE) return nullptr;
        while (next_rec[role] < m_count) {
            const Access & a = m_acc[next_rec[role]++];
            if (a.role != role) continue;
            //The write half of a read-modify-write is the next access of the
            //same role, to the same address
            if (kind == K_RMW && a.kind == K_READ) {
                unsigned int j = next_rec[role];
                while (j < m_count && m_acc[j].role != role) j++;
                if (j < m_count && m_acc[j].kind == K_WRITE && m_acc[j].address == a.address)
                    next_rec[role] = j + 1;
            }
            return a.reply;
        }
        return nullptr;
    };

    //Counted from m_start
    uint32_t t = 0;
    for (unsigned int i = 0; i < n; i++) {
        const Step & s = steps[i];
        const bool prefetch = (i == n - 1);
        const BusReply * reply = prefetch ? prefetch_reply : take(s.role, s.kind);
        const uint32_t strobe = t + ((uint32_t)s.gap + s.strobe) * TICKS_PER_HALF;
        if (s.kind == K_RMW) {
            const uint32_t rel = reply_time(strobe, K_READ, false, reply) + RELEASE_HALVES * TICKS_PER_HALF;
            const uint32_t strobe_w = rel + (uint32_t)s.r2w * TICKS_PER_HALF;
            t = reply_time(strobe_w, K_WRITE, true, reply) + RELEASE_HALVES * TICKS_PER_HALF;
        } else {
            t = reply_time(strobe, s.kind, false, reply) + RELEASE_HALVES * TICKS_PER_HALF;
        }
    }
    m_count = 0;

    const uint32_t advance = t + (uint32_t)VM1_TAIL[form] * TICKS_PER_HALF;
    m_start += advance;
    if (m_phase_window) m_phase = (m_phase + advance) % m_phase_window;

    const uint64_t clocks = (m_start - m_now) / TICKS_PER_CLOCK;
    m_now += clocks * TICKS_PER_CLOCK;
    return (int)clocks;
}

void Vm1BusTiming::idle(unsigned int clocks)
{
    m_now += (uint64_t)clocks * TICKS_PER_CLOCK;
    if (m_start < m_now) { m_start = m_now; m_phase_window = 0; }
}

unsigned int Vm1BusTiming::steps_of(unsigned int form, const Step ** steps)
{
    if (form >= F_COUNT || VM1_COUNT[form] == 0) return 0;
    *steps = &VM1_STEPS[VM1_FIRST[form]];
    return VM1_COUNT[form];
}

// Mirrors form_key() of tools/bk-timing/extract.py
unsigned int Vm1BusTiming::form_of(uint16_t w, bool taken)
{
    auto spec = [](unsigned int sp) { return ((sp >> 3) & 7) * 2 + ((sp & 7) == 7 ? 1 : 0); };

    static const signed char double_index[16] = { -1, 0, 1, 2, 3, 4, 5, -1, -1, 6, 7, 8, 9, 10, 11, -1 };
    const int di = double_index[w >> 12];
    if (di >= 0) return F_DOUBLE + ((unsigned)di * 16 + spec((w >> 6) & 077)) * 16 + spec(w & 077);

    //Single operand instructions by w >> 6, built once
    static const struct SingleIndex {
        signed char index[02000];
        SingleIndex() {
            static const uint16_t ops[28] = {
                00050, 00051, 00052, 00053, 00054, 00055, 00056, 00057, 00060, 00061,
                00062, 00063, 00003, 00067, 01050, 01051, 01052, 01053, 01054, 01055,
                01056, 01057, 01060, 01061, 01062, 01063, 01064, 01067 };
            for (unsigned int i = 0; i < 02000; i++) index[i] = -1;
            for (int i = 0; i < 28; i++) index[ops[i]] = (signed char)i;
        }
    } single;
    const int si = single.index[(w >> 6) & 01777];
    if (si >= 0) return F_SINGLE + (unsigned)si * 16 + spec(w & 077);

    if ((w & 0177000) == 0074000) return F_XOR + spec(w & 077);
    if ((w & 0177700) == 0000100) return F_JMP + spec(w & 077);
    if ((w & 0177000) == 0004000) return F_JSR + spec(w & 077);
    if ((w & 0177770) == 0000200) return F_RTS;
    if ((w & 0177000) == 0077000) return taken ? F_SOB_TAKEN : F_SOB_NOT;
    const unsigned int b = w & 0177400;
    if ((b >= 0000400 && b <= 0003400) || (b >= 0100000 && b <= 0103400))
        return taken ? F_BR_TAKEN : F_BR_NOT;
    if (b == 0104000 || b == 0104400 || w == 0000003 || w == 0000004 || w == 0000000) return F_TRAP;
    if (w == 0000002) return F_RTI;
    if (w == 0000006) return F_RTT;
    if ((w & 0177700) == 0006400) return F_MARK;
    if ((w & 0177740) == 0000240) return (w & 020) ? F_CC_SET : F_CC_CLEAR;
    if (w == 0000001) return F_WAIT;
    if (w == 0000005) return F_RESET;
    return F_COUNT;
}
