// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2023-2026 Mikhail Revzin <p3.141592653589793238462643@gmail.com>
// Part of the eCat3 project: https://github.com/Ptr314/ecat3
// Description: bus cycle timing of the К1801ВМ1 and К1801ВМ2 (timing = vm1, vm2)

#include "vm1_timing.h"
#include "emulator/core.h"

// Generated by tools/bk-timing/emit_inc.py from a simulation of the chip:
// VM1_STEPS, VM1_FIRST, VM1_COUNT and VM1_TAIL
#include "vm1_timing_table.inc"
// The same of the К1801ВМ2, tools/vm2-timing/emit_inc.py: VM2_STEPS, VM2_FIRST,
// VM2_COUNT and VM2_TAIL, in CLC clocks
#include "vm2_timing_table.inc"

Vm1BusTiming::Vm1BusTiming(unsigned int clock_hz, Chip chip)
    : m_chip(chip)
    , m_clock_hz(clock_hz)
{
    if (m_chip == CHIP_VM2) align_vm2();
}

// ВМ2: the chip's strobes, and so its releases, come on every other CLC (the
// edges of f1, CLC halved). The tables are measured from such a release, and
// a memory that answers on the other edges (the КЦГД) is only noticed on the
// next one of these: m_start, the release the next instruction counts from,
// stays on an odd clock
void Vm1BusTiming::align_vm2()
{
    if (((m_start / TICKS_PER_CLOCK) & 1) == 0) m_start += TICKS_PER_CLOCK;
    m_s0 = m_start;
    m_kind2 = K_READ;
    m_flags2 = F2_PREV_DATA_FREE;
    m_phase_window = 0;
}

// From the moment the ВМ2 notices RPLY to the release of its strobe, CLC
static const int VM2_RELEASE_READ = 4;
static const int VM2_RELEASE_WRITE = 3;
// The least the ВМ2 waits from a release to its next SYNC, by the kind of the
// cycle released: the bus is free a clock later after a write. Between two
// instructions, after a data read the previous one ended with, 7: the
// microprogram takes the word in before anything else
static const int VM2_BUS_GAP[3] = { 3, 4, 4 };
static const int VM2_GAP_AFTER_DATA = 7;
// The earliest first step a form may have when the previous form had data
// cycles: only after a form without them (SEC, a branch) does an
// instruction start sooner, and when it cannot, the whole of it starts later
static const int VM2_EARLY_LIMIT = 3;

// The ВМ2 has two things to wait for, the bus and its microprogram, and runs
// a cycle when both are ready. The tables are measured where the bus waits
// for nothing (after SEC, with a static memory), and three rules, found by
// putting the chip against the КЦГД video memory and against a static one,
// take the other cases (tools/vm2-timing, model.py):
// - an instruction starts (s0) when the previous one's tail has run out; the
//   tail runs from the release of the previous one's last cycle, except for a
//   form without data cycles (SEC, MUL R, a branch), whose microprogram does
//   not wait for its prefetch and runs its tail from when a static memory
//   would have released it (strobe + VM2_RELEASE_READ); its first SYNC comes
//   its own gap after s0, but not before the bus allows (VM2_BUS_GAP, and
//   VM2_GAP_AFTER_DATA after a data read that ended the previous one);
// - a form whose own first gap is shorter than VM2_EARLY_LIMIT has it only
//   after a form without data cycles; after any other the whole instruction
//   starts that much later (s0 moves);
// - a write before any data read of its instruction strobes DOUT not before
//   s0 + the step's anchor (r2w of a K_WRITE step), nor before SYNC + strobe;
// - an unaddressed read (IAKO, R_NONE) releases r2w clocks after its DIN.
// Everything else is the chain of the ВМ1: SYNC a fixed gap after the
// previous release, the release when the memory has replied

uint32_t Vm1BusTiming::release_vm2(uint32_t strobe, uint8_t kind, const BusReply * reply, WaitSource * wait,
                                   unsigned int address)
{
    uint32_t rply = strobe;                     //a static memory answers at once
    if (wait != nullptr) {
        //The device is clocked up to m_now; the strobe is m_start + strobe
        const uint64_t at = m_start + strobe - m_now;
        const unsigned int clocks = wait->wait_states(address, kind != K_READ, (unsigned int)(at / TICKS_PER_CLOCK));
        if (clocks != 0) rply = strobe + clocks * TICKS_PER_CLOCK;
    } else if (reply != nullptr) {
        rply = reply_time(strobe, kind, false, reply);
    }
    //Noticed on the next edge of the strobe's own parity
    uint32_t d = (rply - strobe + TICKS_PER_CLOCK - 1) / TICKS_PER_CLOCK;
    d += d & 1;
    return strobe + (d + (kind == K_READ ? VM2_RELEASE_READ : VM2_RELEASE_WRITE)) * TICKS_PER_CLOCK;
}

// A processor half clock after the strobe for a read, a full clock for a
// write: what the replica does with a memory that answers at once
static const int FAST_READ_HALVES = 1;
static const int FAST_WRITE_HALVES = 2;
// From RPLY to the release of the strobe
static const int RELEASE_HALVES = 3;

const Vm1BusTiming::ReplyTicks * Vm1BusTiming::ticks_of(const BusReply * reply)
{
    for (ReplyTicks & c : m_conv)
        if (c.reply == reply) return &c;
    for (ReplyTicks & c : m_conv)
        if (c.reply == nullptr) {
            //ns -> ticks, rounded to the nearest: 12 ticks a clock
            const uint64_t hz = (uint64_t)m_clock_hz * TICKS_PER_CLOCK;
            auto conv = [hz](unsigned int ns) {
                return (uint32_t)(((uint64_t)ns * hz + 500000000ull) / 1000000000ull);
            };
            c.reply = reply;
            c.window = conv(reply->window_ns);
            c.setup_read = conv(reply->setup_read_ns);
            c.setup_write = conv(reply->setup_write_ns);
            c.setup_rmw = conv(reply->setup_rmw_ns);
            c.delay = conv(reply->reply_ns);
            c.rmw_extra = reply->rmw_extra * TICKS_PER_HALF;
            return &c;
        }
    return nullptr;     // more reply kinds than a machine has ever had
}

uint32_t Vm1BusTiming::phase_of_start(uint32_t window)
{
    if (m_phase_window != window) {
        m_phase_window = window;
        m_phase = (uint32_t)(m_start % window);
    }
    return m_phase;
}

uint32_t Vm1BusTiming::reply_time(uint32_t strobe, uint8_t kind, bool rmw_write, const BusReply * reply)
{
    const ReplyTicks * r = (reply != nullptr) ? ticks_of(reply) : nullptr;
    if (r == nullptr || r->window == 0) {
        if (kind == K_READ) return strobe + FAST_READ_HALVES * TICKS_PER_HALF;
        return strobe + FAST_WRITE_HALVES * TICKS_PER_HALF + (rmw_write && r ? r->rmw_extra : 0);
    }
    const uint32_t setup = (kind == K_READ) ? r->setup_read : (rmw_write ? r->setup_rmw : r->setup_write);
    //The first point of the controller's cycle at or after the strobe plus its
    //setup; m_start sits at phase_of_start() within that cycle
    const uint32_t x = strobe + setup;
    const uint32_t into = (phase_of_start(r->window) + x) % r->window;
    const uint32_t point = x + (into ? r->window - into : 0);
    //The processor takes RPLY on its own clock edges; m_start is on one
    const uint32_t seen = point + r->delay;
    return (seen + TICKS_PER_HALF - 1) / TICKS_PER_HALF * TICKS_PER_HALF;
}

int Vm1BusTiming::finish(unsigned int form, const BusReply * prefetch_reply, bool skip_opcode,
                         WaitSource * prefetch_wait, unsigned int prefetch_address, unsigned int extra_tail)
{
    const bool vm2 = (m_chip == CHIP_VM2);
    const Step * steps = nullptr;
    const unsigned int n = vm2 ? steps2_of(form, &steps) : steps_of(form, &steps);
    if (n == 0) {
        m_count = 0;
        return -1;
    }

    //Records are matched to the steps of their own role in order: the chip
    //and the emulator agree on the order of the data cycles and on the order
    //of the instruction stream words, not necessarily on how the two interleave
    unsigned int next_rec[2] = {0, 0};
    if (skip_opcode)
        while (next_rec[R_STREAM] < m_count && m_acc[next_rec[R_STREAM]++].role != R_STREAM) {}
    auto take = [this, &next_rec](uint8_t role, uint8_t kind) -> const Access * {
        if (role == R_NONE || role == R_PREFETCH) return nullptr;
        while (next_rec[role] < m_count) {
            const Access & a = m_acc[next_rec[role]++];
            if (a.role != role) continue;
            //The write half of a read-modify-write is the next access of the
            //same role, to the same address
            if (kind == K_RMW && a.kind == K_READ) {
                unsigned int j = next_rec[role];
                while (j < m_count && m_acc[j].role != role) j++;
                if (j < m_count && m_acc[j].kind == K_WRITE && m_acc[j].address == a.address)
                    next_rec[role] = j + 1;
            }
            return &a;
        }
        return nullptr;
    };

    //Counted from m_start
    uint32_t t = 0;
    if (vm2) {
        //m_start is the previous release here, m_s0 where this instruction
        //starts, m_kind2 the kind of the cycle released last. s0 may lie
        //before m_start: its offset is kept signed
        int64_t s0 = (int64_t)m_s0 - (int64_t)m_start;
        if (!(m_flags2 & F2_PREV_DATA_FREE) && steps[0].gap < VM2_EARLY_LIMIT)
            s0 += (int64_t)(VM2_EARLY_LIMIT - steps[0].gap) * TICKS_PER_CLOCK;
        bool data_read = false;
        bool data_free = true;              //no data cycle: the tail overlaps the last one
        uint32_t last_strobe = 0;
        for (unsigned int i = 0; i < n; i++) {
            const Step & s = steps[i];
            int64_t sync = (int64_t)t + (int64_t)s.gap * TICKS_PER_CLOCK;
            if (i == 0) {
                sync = s0 + (int64_t)s.gap * TICKS_PER_CLOCK;
                const int64_t bus = (int64_t)((m_flags2 & F2_LAST_DATA_READ) ? VM2_GAP_AFTER_DATA
                                                                              : VM2_BUS_GAP[m_kind2]) * TICKS_PER_CLOCK;
                if (sync < bus) sync = bus;
            }
            const BusReply * reply = nullptr;
            WaitSource * wait = nullptr;
            unsigned int address = 0;
            if (s.role == R_PREFETCH) {
                reply = prefetch_reply; wait = prefetch_wait; address = prefetch_address;
            } else if (const Access * a = take(s.role, s.kind)) {
                reply = a->reply; wait = a->wait; address = a->address;
            }
            int64_t strobe = sync + (int64_t)s.strobe * TICKS_PER_CLOCK;
            if (s.kind == K_WRITE && s.r2w != 0 && !data_read) {
                const int64_t ready = s0 + (int64_t)s.r2w * TICKS_PER_CLOCK;
                if (strobe < ready) strobe = ready;
            }
            last_strobe = (uint32_t)strobe;
            if (s.role == R_NONE) {
                t = (uint32_t)strobe + (uint32_t)s.r2w * TICKS_PER_CLOCK;
            } else if (s.kind == K_RMW) {
                const uint32_t rel = release_vm2((uint32_t)strobe, K_READ, reply, wait, address);
                t = release_vm2(rel + (uint32_t)s.r2w * TICKS_PER_CLOCK, K_WRITE, reply, wait, address);
            } else {
                t = release_vm2((uint32_t)strobe, s.kind, reply, wait, address);
            }
            if (s.role == R_NONE) data_free = false;
            if (s.role == R_DATA) {
                data_free = false;
                if (s.kind != K_WRITE) data_read = true;
            }
        }
        m_count = 0;
        const uint64_t tail = ((uint64_t)tail2_of(form) + extra_tail) * TICKS_PER_CLOCK;
        const uint64_t from = m_start + (data_free ? (uint64_t)last_strobe + VM2_RELEASE_READ * TICKS_PER_CLOCK : t);
        m_start += t;
        m_s0 = from + tail;
        m_kind2 = steps[n - 1].kind;
        m_flags2 = (uint8_t)((data_free ? F2_PREV_DATA_FREE : 0) |
                             ((steps[n - 1].role == R_DATA && steps[n - 1].kind == K_READ) ? F2_LAST_DATA_READ : 0));
        m_phase_window = 0;
        //The instruction ends when its tail does, or its last cycle
        const uint64_t end = (m_s0 > m_start) ? m_s0 : m_start;
        const uint64_t clocks = (end > m_now) ? (end - m_now) / TICKS_PER_CLOCK : 0;
        m_now += clocks * TICKS_PER_CLOCK;
        return (int)clocks;
    }
    for (unsigned int i = 0; i < n; i++) {
        const Step & s = steps[i];
        const bool prefetch = (i == n - 1);
        const Access * a = prefetch ? nullptr : take(s.role, s.kind);
        const BusReply * reply = prefetch ? prefetch_reply : (a ? a->reply : nullptr);
        const uint32_t strobe = t + ((uint32_t)s.gap + s.strobe) * TICKS_PER_HALF;
        if (s.kind == K_RMW) {
            const uint32_t rel = reply_time(strobe, K_READ, false, reply) + RELEASE_HALVES * TICKS_PER_HALF;
            const uint32_t strobe_w = rel + (uint32_t)s.r2w * TICKS_PER_HALF;
            t = reply_time(strobe_w, K_WRITE, true, reply) + RELEASE_HALVES * TICKS_PER_HALF;
        } else {
            t = reply_time(strobe, s.kind, false, reply) + RELEASE_HALVES * TICKS_PER_HALF;
        }
    }
    m_count = 0;

    const uint32_t advance = t + (uint32_t)VM1_TAIL[form] * TICKS_PER_HALF;
    m_start += advance;
    if (m_phase_window) m_phase = (m_phase + advance) % m_phase_window;

    const uint64_t clocks = (m_start - m_now) / TICKS_PER_CLOCK;
    m_now += clocks * TICKS_PER_CLOCK;
    return (int)clocks;
}

void Vm1BusTiming::idle(unsigned int clocks)
{
    m_now += (uint64_t)clocks * TICKS_PER_CLOCK;
    if (m_chip == CHIP_VM2) {
        //The chain is idle from the end of the last tail on
        if (m_start < m_now && m_s0 < m_now) {
            m_start = m_now;
            align_vm2();
        }
        return;
    }
    if (m_start < m_now) {
        m_start = m_now;
        m_phase_window = 0;
        if (m_chip == CHIP_VM2) align_vm2();
    }
}

unsigned int Vm1BusTiming::steps_of(unsigned int form, const Step ** steps)
{
    if (form >= F_COUNT || VM1_COUNT[form] == 0) return 0;
    *steps = &VM1_STEPS[VM1_FIRST[form]];
    return VM1_COUNT[form];
}

unsigned int Vm1BusTiming::steps2_of(unsigned int form, const Step ** steps)
{
    if (form >= F2_COUNT || VM2_COUNT[form] == 0) return 0;
    *steps = &VM2_STEPS[VM2_FIRST[form]];
    return VM2_COUNT[form];
}

unsigned int Vm1BusTiming::tail2_of(unsigned int form)
{
    return (form < F2_COUNT) ? VM2_TAIL[form] : 0;
}

// Mirrors form_key() of tools/bk-timing/extract.py
unsigned int Vm1BusTiming::form_of(uint16_t w, bool taken)
{
    auto spec = [](unsigned int sp) { return ((sp >> 3) & 7) * 2 + ((sp & 7) == 7 ? 1 : 0); };

    static const signed char double_index[16] = { -1, 0, 1, 2, 3, 4, 5, -1, -1, 6, 7, 8, 9, 10, 11, -1 };
    const int di = double_index[w >> 12];
    if (di >= 0) return F_DOUBLE + ((unsigned)di * 16 + spec((w >> 6) & 077)) * 16 + spec(w & 077);

    //Single operand instructions by w >> 6, built once
    static const struct SingleIndex {
        signed char index[02000];
        SingleIndex() {
            static const uint16_t ops[28] = {
                00050, 00051, 00052, 00053, 00054, 00055, 00056, 00057, 00060, 00061,
                00062, 00063, 00003, 00067, 01050, 01051, 01052, 01053, 01054, 01055,
                01056, 01057, 01060, 01061, 01062, 01063, 01064, 01067 };
            for (unsigned int i = 0; i < 02000; i++) index[i] = -1;
            for (int i = 0; i < 28; i++) index[ops[i]] = (signed char)i;
        }
    } single;
    const int si = single.index[(w >> 6) & 01777];
    if (si >= 0) return F_SINGLE + (unsigned)si * 16 + spec(w & 077);

    if ((w & 0177000) == 0074000) return F_XOR + spec(w & 077);
    if ((w & 0177700) == 0000100) return F_JMP + spec(w & 077);
    if ((w & 0177000) == 0004000) return F_JSR + spec(w & 077);
    if ((w & 0177770) == 0000200) return F_RTS;
    if ((w & 0177000) == 0077000) return taken ? F_SOB_TAKEN : F_SOB_NOT;
    const unsigned int b = w & 0177400;
    if ((b >= 0000400 && b <= 0003400) || (b >= 0100000 && b <= 0103400))
        return taken ? F_BR_TAKEN : F_BR_NOT;
    if (b == 0104000 || b == 0104400 || w == 0000003 || w == 0000004 || w == 0000000) return F_TRAP;
    if (w == 0000002) return F_RTI;
    if (w == 0000006) return F_RTT;
    if ((w & 0177700) == 0006400) return F_MARK;
    if ((w & 0177740) == 0000240) return (w & 020) ? F_CC_SET : F_CC_CLEAR;
    if (w == 0000001) return F_WAIT;
    if (w == 0000005) return F_RESET;
    return F_COUNT;
}

// Mirrors form_key() of tools/vm2-timing/extract.py
unsigned int Vm1BusTiming::form2_of(uint16_t w, bool taken, bool div_v)
{
    auto spec = [](unsigned int sp) { return ((sp >> 3) & 7) * 2 + ((sp & 7) == 7 ? 1 : 0); };
    if ((w & 0170000) == 0070000) {
        const unsigned int op = (w >> 9) & 7;
        if (op <= 3) {
            const unsigned int e = (op == 1 && div_v) ? 4 : op;
            return F2_EIS + e * 16 + spec(w & 077);
        }
    }
    const unsigned int f = form_of(w, taken);
    if (f < F_XOR) return f;                                //double and single: the same place
    if (f < F_COUNT) return f - F_XOR + F2_XOR;
    return F2_COUNT;
}
